// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFTi9V_JOxX30iIybqAvHGMpu_iDNz3cA',
    appId: '1:1078621587478:web:c3985373f1a56189324d37',
    messagingSenderId: '1078621587478',
    projectId: 'vijay-13641',
    authDomain: 'vijay-13641.firebaseapp.com',
    storageBucket: 'vijay-13641.appspot.com',
    measurementId: 'G-H5H6B42RF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6TmvYTtgCAbqfSVgxFIBWWKLx4aPD9k',
    appId: '1:1078621587478:android:553e0ca0b83537ee324d37',
    messagingSenderId: '1078621587478',
    projectId: 'vijay-13641',
    storageBucket: 'vijay-13641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxnigx8slXw49BomUKl1MxHB9dRd4gLZY',
    appId: '1:1078621587478:ios:5f2012b55e280f3a324d37',
    messagingSenderId: '1078621587478',
    projectId: 'vijay-13641',
    storageBucket: 'vijay-13641.appspot.com',
    iosBundleId: 'com.example.vijay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxnigx8slXw49BomUKl1MxHB9dRd4gLZY',
    appId: '1:1078621587478:ios:bd07fc9e94964d78324d37',
    messagingSenderId: '1078621587478',
    projectId: 'vijay-13641',
    storageBucket: 'vijay-13641.appspot.com',
    iosBundleId: 'com.example.vijay.RunnerTests',
  );
}
